### ISSUE TITLE
Can't find snapshots when running test.sh

### ISSUE THREAD

**Issue by rdruss** [openshiftio-vertx-boosters/vertx-circuit-breaker-booster#34]
[ERROR] Failed to execute goal on project integration-tests: Could not resolve dependencies for project io.openshift.booster:integration-tests:jar:21-SNAPSHOT: The following artifacts could not be resolved: io.openshift.booster:name-service:jar:21-SNAPSHOT, io.openshift.booster:greeting-service:jar:21-SNAPSHOT: Failure to find io.openshift.booster:name-service:jar:21-SNAPSHOT in https://maven.repository.redhat.com/ga/ was cached in the local repository, resolution will not be reattempted until the update interval of redhat-ga has elapsed or updates are forced

If you run mvn install from project root before running mvn verify from the integration-tests directory, then everything works.

**Comment by cescoffier** [comment]
Fixed by #35
